# Generated by Django 4.2.16 on 2024-09-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_fish_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
